### ISSUE TITLE
Leefbare dorpen analysis Home-Work FOD data

### ISSUE THREAD

**Issue by wimmichiels76** [wimmichiels76/personalwork#2]
use the FOD data to analyse the existing situation on home-work trips in QGIS and excel

**Comment by he-ulg** [comment]
This is me.

**Comment by wimmichiels76** [comment]
An analysis is the result of the OD in QGIS + applied to routeplanner for profiles "bike fast", "bike regular" and "car".

result = 15 geopackages

bike fast 'asis'
bike regular 'asis'
car 'asis'
car---switchto--->bike fast
car---switchto--->bike regular


Landen
Tienen
Sint-Truiden

**Comment by wimmichiels76** [comment]
<5km = 90%
<20km = 50%
<30km = 25%

**Comment by he-ulg** [comment]
"Y015_present_11_03_2020" Qgis project file including 15 requested layers was created and can be found at:
...\ANYWAYS Dropbox\projects\Y015-getedorpen\Qgis\
